version: "3"

services:
  spec:
    restart: "no"
    build:
      context: .
      args:
        - ZONEMASTER_ENGINE_VERSION=$ZONEMASTER_ENGINE_VERSION
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app\""
    volumes:
      - .:/app

  pages:
    extends: spec
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app pages\""
