version: "3"

services:
  spec:
    restart: "no"
    build:
      context: .
      args:
        - ZONEMASTER_ENGINE_VERSION=$ZONEMASTER_ENGINE_VERSION
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app\""
    volumes:
      - .:/app

  pages:
    extends: spec
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app pages\""

  pageserver:
    extends: spec
    command: "sh -c \"cd /app/_site ; python3 -m http.server 8080 -b 0.0.0.0\""
    networks:
      - rst

networks:
  rst:
    external: true
