version: "3"

services:
  spec:
    restart: "no"
    build:
      context: .
      args:
        - ZONEMASTER_ENGINE_VERSION=$ZONEMASTER_ENGINE_VERSION
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app\""
    volumes:
      - .:/app

  pages:
    extends: spec
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app pages\""

  spec-persistent:
    extends: spec
    command: "sh -c \"git config --global --add safe.directory /app ; make -C /app includes yaml lint json ; cp -vf /app/rst-test-specs.yaml /tmp/rst/\""
    volumes:
      - rst:/tmp/rst

volumes:
  rst:
    external: true
    name: rst-test-spec-persistent

