#!/bin/sh
SITEDIR="_site"

rm -rf "$SITEDIR"
mkdir "$SITEDIR"

pandoc \
    --from markdown \
    --to html \
    --standalone \
    --embed-resources=true \
    --metadata title="Registry System Testing (RST) Test Specifications" \
    --css=inc/html/style.css \
    --output="$SITEDIR/index.html" \
    etc/index.md

make all

mv rst.json rst-test-specs.html rst-test-specs.json rst-test-specs.yaml "$SITEDIR/"

chmod -R 0755 "$SITEDIR"
