#!/bin/bash

SITEDIR="_site"

rm -rf "$SITEDIR"
mkdir "$SITEDIR"

git config --global --add safe.directory /app

CURRENT_RELEASE="$(git tag | tail -1)"

if [ -z "$CURRENT_RELEASE" ] ; then
    echo "No release tag found! Tag list follows..."
    git tag --list
    exit 1
fi

echo "Current release is $CURRENT_RELEASE"

echo "Creating index file..."
gpp -x "-DRELEASE=$CURRENT_RELEASE" etc/index.md | pandoc \
    --from markdown \
    --to html \
    --standalone \
    --embed-resources=true \
    --metadata title="ICANN Registry System Testing (RST) Test Specifications" \
    --css=inc/html/style.css \
    --output="$SITEDIR/index.html"

echo "Syncing spec file..."
curl --silent --fail --location --output "$SITEDIR/rst-test-specs.html" "https://github.com/icann/rst-test-specs/releases/download/$CURRENT_RELEASE/rst-test-specs.html"

echo "Generating EPP extension data..."
mkdir "$SITEDIR/epp-extensions"
yq -o json epp-extensions/epp-extensions.yaml > "$SITEDIR/epp-extensions/epp-extensions.json"
cp -R epp-extensions/xsd "$SITEDIR/epp-extensions/"
tools/generate-superschema.pl > "$SITEDIR/epp-extensions/xsd/super.xsd"

cp rdapct_config*.json "$SITEDIR/"

chmod -R 0755 "$SITEDIR"

echo "done"
