name: build-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: docker compose up pages

      - name: configure
        uses: actions/configure-pages@v3

      - name: upload
        uses: actions/upload-pages-artifact@v1

      - name: deploy
        uses: actions/deploy-pages@v4
