name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build pages
        run: docker compose up pages

      - name: configure pages
        uses: actions/configure-pages@v3

      - name: upload pages
        uses: actions/upload-pages-artifact@v1
