name: build

on:
  push:
    branches: [ "Xmain" ] # bogus branch name to stop this action running on every push
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: apk update
        run: apk update

      - name: install deps
        run: |
          apk add make gcc musl-dev perl perl-file-slurp perl-json-xs \
            perl-yaml perl-yaml-libyaml perl-text-unidecode perl-xml-libxml \
            perl-uri perl-app-cpanminus pandoc git graphviz perl-dev

          cpanm --notest HTML::Tiny GraphViz2

          wget -qO - https://github.com/logological/gpp/releases/download/2.28/gpp-2.28.tar.bz2 | tar xj
          cd gpp-2.28
          ./configure
          make install
          rm -rf ../gpp-2.28

      - name: make
        run: make
