name: lint

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint
        run: docker compose run lint
