name: lint

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lint
        run: docker compose run lint
