name: Weekly update of the main branch
on:
  workflow_dispatch:
  schedule:
    - cron: "00 06 * * 3"

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: merge
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
