name: monitor-extension-registry

on:
  schedule:
    - cron: "24 04 * * 3"

  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install tools
        run: apk -q add xq curl jq nodejs

      - name: retrieve registry
        run: curl --silent --fail --remote-name https://www.iana.org/assignments/epp-extensions/epp-extensions.xml

      - name: extract timestamps
        id: get_last_updated
        run: |
          date +registry_last_updated=%s -d $(xq -x /registry/updated epp-extensions.xml) >> $GITHUB_OUTPUT
          date +extension_list_last_updated=%s -d $(jq -r ".[\"last-updated\"]" < epp-extensions/epp-extensions.json) >> $GITHUB_OUTPUT

      - name: create isse
        if: ${{ steps.get_last_updated.outputs.registry_last_updated > steps.get_last_updated.outputs.extension_list_last_updated }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/epp-extenstion-registry-update.md
